#!/usr/bin/env bash

set -euo pipefail

BASHRC_PATH="${HOME}/.bashrc"
MARKER_START="# >>> confighelper managed start >>>"
MARKER_END="# <<< confighelper managed end <<<"

command_path() {
  local tool="$1"
  command -v "${tool}" 2>/dev/null || true
}

append_line() {
  local __var_name="$1"
  local __line="$2"
  printf -v "${__var_name}" '%s%s\n' "${!__var_name}" "${__line}"
}

path_contains_dir() {
  local dir="$1"
  [[ ":${PATH}:" == *":${dir}:"* ]]
}

append_managed_block() {
  local block_content="$1"
  local tmp_file
  tmp_file="$(mktemp)"

  if [[ -f "${BASHRC_PATH}" ]]; then
    awk -v start="${MARKER_START}" -v end="${MARKER_END}" '
      $0 == start { skip=1; next }
      $0 == end { skip=0; next }
      !skip { print }
    ' "${BASHRC_PATH}" > "${tmp_file}"
  fi

  {
    echo "${MARKER_START}"
    echo "# Generated by ConfigHelper. Safe to re-run."
    echo "${block_content}"
    echo "${MARKER_END}"
  } >> "${tmp_file}"

  mv "${tmp_file}" "${BASHRC_PATH}"
}

configure_env_for_detected_tools() {
  echo "[Phase 2] Detecting tools and preparing shell configuration..."

  local block=""
  local seen_dirs=","
  local py_path
  local node_path
  local java_path
  local go_path
  local kubelet_path
  local conda_path
  local dir_path

  conda_path="$(command_path conda)"
  py_path="$(command_path python3)"
  node_path="$(command_path node)"
  java_path="$(command_path java)"
  go_path="$(command_path go)"
  kubelet_path="$(command_path kubelet)"

  if [[ -n "${conda_path}" ]]; then
    dir_path="$(dirname "${conda_path}")"
    append_line block "# conda detected"
    if [[ "${seen_dirs}" != *",${dir_path},"* ]] && ! path_contains_dir "${dir_path}"; then
      append_line block "export PATH=\"${dir_path}:\$PATH\""
      seen_dirs+="${dir_path},"
    fi
  fi
  if [[ -n "${py_path}" ]]; then
    dir_path="$(dirname "${py_path}")"
    append_line block "# python3 detected"
    if [[ "${seen_dirs}" != *",${dir_path},"* ]] && ! path_contains_dir "${dir_path}"; then
      append_line block "export PATH=\"${dir_path}:\$PATH\""
      seen_dirs+="${dir_path},"
    fi
  fi
  if [[ -n "${node_path}" ]]; then
    dir_path="$(dirname "${node_path}")"
    append_line block "# node detected"
    if [[ "${seen_dirs}" != *",${dir_path},"* ]] && ! path_contains_dir "${dir_path}"; then
      append_line block "export PATH=\"${dir_path}:\$PATH\""
      seen_dirs+="${dir_path},"
    fi
  fi
  if [[ -n "${java_path}" ]]; then
    dir_path="$(dirname "${java_path}")"
    append_line block "# java detected"
    if [[ "${seen_dirs}" != *",${dir_path},"* ]] && ! path_contains_dir "${dir_path}"; then
      append_line block "export PATH=\"${dir_path}:\$PATH\""
      seen_dirs+="${dir_path},"
    fi
  fi
  if [[ -n "${go_path}" ]]; then
    dir_path="$(dirname "${go_path}")"
    append_line block "# go detected"
    if [[ "${seen_dirs}" != *",${dir_path},"* ]] && ! path_contains_dir "${dir_path}"; then
      append_line block "export PATH=\"${dir_path}:\$PATH\""
      seen_dirs+="${dir_path},"
    fi
    append_line block "export GOPATH=\"\${HOME}/go\""
    append_line block "export PATH=\"\${GOPATH}/bin:\$PATH\""
  fi
  if [[ -n "${kubelet_path}" ]]; then
    dir_path="$(dirname "${kubelet_path}")"
    append_line block "# kubelet detected"
    if [[ "${seen_dirs}" != *",${dir_path},"* ]] && ! path_contains_dir "${dir_path}"; then
      append_line block "export PATH=\"${dir_path}:\$PATH\""
      seen_dirs+="${dir_path},"
    fi
  fi

  # Optional quality-of-life settings.
  if command -v npm >/dev/null 2>&1; then
    append_line block ""
    append_line block "# npm completion (if available)"
    append_line block "if command -v npm >/dev/null 2>&1; then"
    append_line block "  source <(npm completion 2>/dev/null) || true"
    append_line block "fi"
  fi

  if [[ -z "${block}" ]]; then
    echo "No supported tools detected. Nothing to configure."
    return 0
  fi

  append_managed_block "${block}"
  echo "Updated ${BASHRC_PATH} with managed ConfigHelper block."
}
