#!/usr/bin/env bash

set -euo pipefail

BASHRC_PATH="${HOME}/.bashrc"
MARKER_START="# >>> confighelper managed start >>>"
MARKER_END="# <<< confighelper managed end <<<"

command_path() {
  local tool="$1"
  command -v "${tool}" 2>/dev/null || true
}

append_managed_block() {
  local block_content="$1"
  local tmp_file
  tmp_file="$(mktemp)"

  if [[ -f "${BASHRC_PATH}" ]]; then
    awk -v start="${MARKER_START}" -v end="${MARKER_END}" '
      $0 == start { skip=1; next }
      $0 == end { skip=0; next }
      !skip { print }
    ' "${BASHRC_PATH}" > "${tmp_file}"
  fi

  {
    echo ""
    echo "${MARKER_START}"
    echo "# Generated by ConfigHelper. Safe to re-run."
    echo "${block_content}"
    echo "${MARKER_END}"
  } >> "${tmp_file}"

  mv "${tmp_file}" "${BASHRC_PATH}"
}

configure_env_for_detected_tools() {
  echo "[Phase 2] Detecting tools and preparing shell configuration..."

  local block=""
  local py_path
  local node_path
  local java_path
  local go_path
  local kubelet_path
  local conda_path

  conda_path="$(command_path conda)"
  py_path="$(command_path python3)"
  node_path="$(command_path node)"
  java_path="$(command_path java)"
  go_path="$(command_path go)"
  kubelet_path="$(command_path kubelet)"

  if [[ -n "${conda_path}" ]]; then
    block+=$'# conda detected\n'
    block+=$'export PATH="'"$(dirname "${conda_path}")"':$PATH"\n'
  fi
  if [[ -n "${py_path}" ]]; then
    block+=$'# python3 detected\n'
    block+=$'export PATH="'"$(dirname "${py_path}")"':$PATH"\n'
  fi
  if [[ -n "${node_path}" ]]; then
    block+=$'# node detected\n'
    block+=$'export PATH="'"$(dirname "${node_path}")"':$PATH"\n'
  fi
  if [[ -n "${java_path}" ]]; then
    block+=$'# java detected\n'
    block+=$'export PATH="'"$(dirname "${java_path}")"':$PATH"\n'
  fi
  if [[ -n "${go_path}" ]]; then
    block+=$'# go detected\n'
    block+=$'export PATH="'"$(dirname "${go_path}")"':$PATH"\n'
    block+=$'export GOPATH="${HOME}/go"\n'
    block+=$'export PATH="${GOPATH}/bin:$PATH"\n'
  fi
  if [[ -n "${kubelet_path}" ]]; then
    block+=$'# kubelet detected\n'
    block+=$'export PATH="'"$(dirname "${kubelet_path}")"':$PATH"\n'
  fi

  # Optional quality-of-life settings.
  if command -v npm >/dev/null 2>&1; then
    block+=$'\n# npm completion (if available)\n'
    block+=$'if command -v npm >/dev/null 2>&1; then\n'
    block+=$'  source <(npm completion 2>/dev/null) || true\n'
    block+=$'fi\n'
  fi

  if [[ -z "${block}" ]]; then
    echo "No supported tools detected. Nothing to configure."
    return 0
  fi

  append_managed_block "${block}"
  echo "Updated ${BASHRC_PATH} with managed ConfigHelper block."
}
